services:
  postgres:
    image: postgres:17
    container_name: perlinadv_postgres_prod
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      target: prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perlinadv_api_prod.rule=Host(`api.sistema.carmenperlin.adv.br`)"
      - "traefik.http.routers.perlinadv_api_prod.entrypoints=websecure"
      - "traefik.http.routers.perlinadv_api_prod.tls.certresolver=default"
    container_name: perlinadv_api_prod
    environment:
      NODE_ENV: "production"
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_DB}?schema=public
      # Optional seeding variables
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
      SEED_ADMIN_NAME: ${SEED_ADMIN_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
      - traefik

  web:
    build:
      context: ./web
      target: prod
      args:
        - VITE_API_URL=https://api.sistema.carmenperlin.adv.br/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perlinadv_web_prod.rule=Host(`sistema.carmenperlin.adv.br`)"
      - "traefik.http.routers.perlinadv_web_prod.entrypoints=websecure"
      - "traefik.http.routers.perlinadv_web_prod.tls.certresolver=default"
    container_name: perlinadv_web_prod
    networks:
      - frontend
      - traefik

networks:
  backend:
  frontend:
  traefik:
    external: true

volumes:
  pgdata_prod:
