services:
  postgres:
    image: postgres:17
    container_name: perlinadv_postgres_dev
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - backend

  api:
    image: node:24-alpine
    container_name: perlinadv_api_dev
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm prisma migrate dev && pnpm prisma db seed && pnpm start:dev"
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_DB}?schema=public
      # Optional seeding variables
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
      SEED_ADMIN_NAME: ${SEED_ADMIN_NAME}
      CI: true
    depends_on:
      - postgres
    ports:
      - "7777:5000"
      - "5555:5555" # Prisma Studio
    networks:
      - backend

  web:
    image: node:24-alpine
    container_name: perlinadv_web_dev
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm start:dev"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_API_URL: ${VITE_API_URL}
      CI: true
    ports:
      - "3333:5173"
    depends_on:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  pgdata_dev:
